package com.tencent.wxcloudrun.dao;

import com.tencent.wxcloudrun.dao.base.BaseShowMetaDataDAO;
import org.apache.ibatis.annotations.Mapper;

/**
 * This class was generated by Ali-Generator
 * @author chengleiyi
 */
@Mapper
public interface ShowMetaDataDAO extends BaseShowMetaDataDAO {
}