package com.tencent.wxcloudrun.service;

import com.tencent.wxcloudrun.model.ShowMetaDataDO;
import org.springframework.beans.BeanUtils;
import org.springframework.stereotype.Service;

/**
 * This class was generated by Ali-Generator
 * @author chengleiyi
 */
@Service
public class ShowMetaDataConverter {

    /**
     * DTO模型转换成DO模型
     * @param showMetaDataDTO
     */
    public ShowMetaDataDO convertFromDTO(ShowMetaDataDTO showMetaDataDTO) {
        ShowMetaDataDO showMetaDataDO = new ShowMetaDataDO();
        BeanUtils.copyProperties(showMetaDataDTO,showMetaDataDO);
        return showMetaDataDO;
    }

    /**
     * DO模型转换成DTO模型
     * @param showMetaDataDO
     */
    public ShowMetaDataDTO convertFromDO(ShowMetaDataDO showMetaDataDO) {
        ShowMetaDataDTO showMetaDataDTO = new ShowMetaDataDTO();
        BeanUtils.copyProperties(showMetaDataDO,showMetaDataDTO);
        return showMetaDataDTO;
    }
}