package com.tencent.wxcloudrun.service;

import java.io.Serializable;
import java.util.Date;
import lombok.Getter;
import lombok.Setter;

/**
 * This class was generated by Ali-Generator
 * @author chengleiyi
 */
public class ShowMetaDataDTO implements Serializable {
    private static final long serialVersionUID = 1L;

    /**
     *   主键
     */
    @Getter
    @Setter
    private Long id;

    /**
     *   创建时间
     */
    @Getter
    @Setter
    private Date gmtCreate;

    /**
     *   修改时间
     */
    @Getter
    @Setter
    private Date gmtModified;

    /**
     */
    @Getter
    @Setter
    private String showCode;

    /**
     */
    @Getter
    @Setter
    private String showName;

    /**
     *   主图
     */
    @Getter
    @Setter
    private String mainPicture;

    /**
     *   渠道
     */
    @Getter
    @Setter
    private String channel;

    /**
     *   最后一场的时间
     */
    @Getter
    @Setter
    private Date lastShowTime;

    /**
     *   状态
     */
    @Getter
    @Setter
    private Byte status;

    /**
     *   排序顺序
     */
    @Getter
    @Setter
    private Integer index;
}